/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    GuideItem: typeof import('./src/components/Guide/GuideItem.vue')['default']
    Header: typeof import('./src/components/Shared/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Base/Search.vue')['default']
    SideBarLeft: typeof import('./src/components/Shared/SideBarLeft.vue')['default']
    SideBarRight: typeof import('./src/components/Shared/SideBarRight.vue')['default']
  }
}
